name: CI

on:
    pull_request:
        branches: [master]
        types: ["opened", "synchronize"]

    merge_group:
        branches: [master]

    workflow_dispatch:

concurrency:
    group: ${{ github.ref }}
    cancel-in-progress: true

jobs:
    e2e:
        name: E2E

        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - uses: ./.github/actions/load-node-modules

            - name: Run e2e tests
              run: DEBUG=pw:browser* PLAYWRIGHT_BROWSERS_PATH=0 pnpm exec playwright test
